name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # Runs every hour, on the hour
    - cron: '0 * * * *' 
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "7"
          feed_list: "https://medium.com/feed/@benthecoder07"